export const GET_KINDOFROOM_LIST = "GET_KINDOFROOM_LIST";
export const GET_KINDOFROOM_LIST_SUCCESS = "GET_KINDOFROOM_LIST_SUCCESS";
export const GET_KINDOFROOM_LIST_FAIL = "GET_KINDOFROOM_LIST_FAIL";

export const CREATE_KINDOFROOM = "CREATE_KINDOFROOM";
export const CREATE_KINDOFROOM_SUCCESS = "CREATE_KINDOFROOM_SUCCESS";
export const CREATE_KINDOFROOM_FAIL = "CREATE_KINDOFROOM_FAIL";

export const DELETE_KINDOFROOM = "DELETE_KINDOFROOM";
export const DELETE_KINDOFROOM_SUCCESS = "DELETE_KINDOFROOM_SUCCESS";
export const DELETE_KINDOFROOM_FAIL = "DELETE_KINDOFROOM_FAIL";

export const KINDOFROOM_OPEN_CLOSE_MODAL = "KINDOFROOM_OPEN_CLOSE_MODAL";
