export const GET_CLINIC_LIST = "GET_CLINIC_LIST";
export const GET_CLINIC_LIST_SUCCESS = "GET_CLINIC_LIST_SUCCESS";
export const GET_CLINIC_LIST_FAIL = "GET_CLINIC_LIST_FAIL";

export const CREATE_CLINIC = "CREATE_CLINIC";
export const CREATE_CLINIC_SUCCESS = "CREATE_CLINIC_SUCCESS";
export const CREATE_CLINIC_FAIL = "CREATE_CLINIC_FAIL";

export const DELETE_CLINIC = "DELETE_CLINIC";
export const DELETE_CLINIC_SUCCESS = "DELETE_CLINIC_SUCCESS";
export const DELETE_CLINIC_FAIL = "DELETE_CLINIC_FAIL";

export const CLINIC_OPEN_CLOSE_MODAL = "CLINIC_OPEN_CLOSE_MODAL";
