export const GET_PATIENT_LIST = "GET_PATIENT_LIST";
export const GET_PATIENT_LIST_SUCCESS = "GET_PATIENT_LIST_SUCCESS";
export const GET_PATIENT_LIST_FAIL = "GET_PATIENT_LIST_FAIL";

export const CREATE_PATIENT = "CREATE_PATIENT";
export const CREATE_PATIENT_SUCCESS = "CREATE_PATIENT_SUCCESS";
export const CREATE_PATIENT_FAIL = "CREATE_PATIENT_FAIL";

export const EDIT_PATIENT = "EDIT_PATIENT";
export const EDIT_PATIENT_SUCCESS = "EDIT_PATIENT_SUCCESS";
export const EDIT_PATIENT_FAIL = "EDIT_PATIENT_FAIL";

export const DELETE_PATIENT = "DELETE_PATIENT";
export const DELETE_PATIENT_SUCCESS = "DELETE_PATIENT_SUCCESS";
export const DELETE_PATIENT_FAIL = "DELETE_PATIENT_FAIL";

export const PATIENT_OPEN_CLOSE_MODAL = "PATIENT_OPEN_CLOSE_MODAL";
