export const GET_SERVICES_LIST = "GET_SERVICES_LIST";
export const GET_SERVICES_LIST_SUCCESS = "GET_SERVICES_LIST_SUCCESS";
export const GET_SERVICES_LIST_FAIL = "GET_SERVICES_LIST_FAIL";

export const CREATE_SERVICES = "CREATE_SERVICES";
export const CREATE_SERVICES_SUCCESS = "CREATE_SERVICES_SUCCESS";
export const CREATE_SERVICES_FAIL = "CREATE_SERVICES_FAIL";

export const DELETE_SERVICES = "DELETE_SERVICES";
export const DELETE_SERVICES_SUCCESS = "DELETE_SERVICES_SUCCESS";
export const DELETE_SERVICES_FAIL = "DELETE_SERVICES_FAIL";

export const SERVICES_OPEN_CLOSE_MODAL = "SERVICES_OPEN_CLOSE_MODAL";
