export const GET_DOCTOR_LIST = "GET_DOCTOR_LIST";
export const GET_DOCTOR_LIST_SUCCESS = "GET_DOCTOR_LIST_SUCCESS";
export const GET_DOCTOR_LIST_FAIL = "GET_DOCTOR_LIST_FAIL";

export const CREATE_DOCTOR = "CREATE_DOCTOR";
export const CREATE_DOCTOR_SUCCESS = "CREATE_DOCTOR_SUCCESS";
export const CREATE_DOCTOR_FAIL = "CREATE_DOCTOR_FAIL";

export const DELETE_DOCTOR = "DELETE_DOCTOR";
export const DELETE_DOCTOR_SUCCESS = "DELETE_DOCTOR_SUCCESS";
export const DELETE_DOCTOR_FAIL = "DELETE_DOCTOR_FAIL";

export const DOCTOR_OPEN_CLOSE_MODAL = "DOCTOR_OPEN_CLOSE_MODAL";
