export const GET_PENDING_MEDICAL_LIST = "GET_PENDING_MEDICAL_LIST";
export const GET_PENDING_MEDICAL_LIST_SUCCESS = "GET_PENDING_MEDICAL_LIST_SUCCESS";
export const GET_PENDING_MEDICAL_LIST_FAIL = "GET_PENDING_MEDICAL_LIST_FAIL";
