export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAIL = "GET_USER_INFO_FAIL";

export const SYNC_USER_INFO = "SYNC_USER_INFO";
export const SYNC_USER_INFO_SUCCESS = "SYNC_USER_INFO_SUCCESS";
export const SYNC_USER_INFO_FAIL = "SYNC_USER_INFO_FAIL";

export const LOGOUT = "LOGOUT";
