export const GET_MEDICINE_LIST = "GET_MEDICINE_LIST";
export const GET_MEDICINE_LIST_SUCCESS = "GET_MEDICINE_LIST_SUCCESS";
export const GET_MEDICINE_LIST_FAIL = "GET_MEDICINE_LIST_FAIL";

export const CREATE_MEDICINE = "CREATE_MEDICINE";
export const CREATE_MEDICINE_SUCCESS = "CREATE_MEDICINE_SUCCESS";
export const CREATE_MEDICINE_FAIL = "CREATE_MEDICINE_FAIL";

export const MEDICINE_OPEN_CLOSE_MODAL = "MEDICINE_OPEN_CLOSE_MODAL";
