export const GET_NOTIFICATION_STATISTICS = "GET_NOTIFICATION_STATISTICS";
export const GET_NOTIFICATION_STATISTICS_SUCCESS = "GET_NOTIFICATION_STATISTICS_SUCCESS";
export const GET_NOTIFICATION_STATISTICS_FAIL = "GET_NOTIFICATION_STATISTICS_FAIL";

export const GET_LIST_NOTIFICATION = "GET_LIST_NOTIFICATION";
export const GET_LIST_NOTIFICATION_SUCCESS = "GET_LIST_NOTIFICATION_SUCCESS";
export const GET_LIST_NOTIFICATION_FAIL = "GET_LIST_NOTIFICATION_FAIL";

export const GET_NOTIFICATION_STATUS = "GET_NOTIFICATION_STATUS";
export const GET_NOTIFICATION_STATUS_SUCCESS = "GET_NOTIFICATION_STATUS_SUCCESS";
export const GET_NOTIFICATION_STATUS_FAIL = "GET_NOTIFICATION_STATUS_FAIL";

export const GET_NOTIFICATION_DETAIL = "GET_NOTIFICATION_DETAIL";
export const GET_NOTIFICATION_DETAIL_SUCCESS = "GET_NOTIFICATION_DETAIL_SUCCESS";
export const GET_NOTIFICATION_DETAIL_FAIL = "GET_NOTIFICATION_DETAIL_FAIL";

export const NOTIFICATION_OPEN_CLOSE_MODAL = "NOTIFICATION_OPEN_CLOSE_MODAL";